config/routes.rb
Rails.application.routes.draw do
resource :shopping_cart

  # get 'cart/add/:id' => 'cart#add',as: :cart_add

  resources :categories
  post '/rate' => 'rater#create', :as => 'rate'
  resources :products
root 'home#index'
  get '/register' => 'users#new'
  post '/register' => 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/account/:id', to: 'users#show', as: 'account'
  get '/account/:id/edit', to: 'users#edit', as: 'modify_account'
  patch '/account/:id', to: 'users#update'
  put '/account/:id', to: 'users#update'
  delete '/account/:id', to: 'users#destroy', as: 'delete_account'

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, :dependent => :destroy
  has_one :shopping_cart,  :dependent => :destroy
  validates :email, uniqueness:{ case_sensitive: false }, length: 2..25
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :password, confirmation: true
  validates :username,presence: true, length: 2..15
  has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: :index

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.admin = false
      if @user.save
        login @user
        redirect_to account_path @user.id, notice: 'Account created.'
      else
        render "new"
      end
  end

  def update
      if @user.update(user_params)
        if current_user.admin
          redirect_to @user, notice: "Account modified."
        else
          redirect_to account_path, notice: "Account modified."
        end
      else
          render "edit" # URL changes to admin/users/:id HOW TO PREVENT THAT??? Use render because of @user.errors that need
          # to be displayed
      end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    if current_user.admin
      redirect_to users_url, notice: "Account deleted."
    else
      redirect_to root_url, notice: "Account deleted."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <% if current_user.admin %>
  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Save changes" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if current_user.admin %>
<h1>Editing User</h1>
<% else %>
<h1>Modify your account</h1>
<% end %>
<%= render 'form', user: @user %>

<% if current_user.admin %>
<%= link_to 'Show', @user %>
<br>
<%= link_to 'Back', users_path %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Admin</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Registration page</h1>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for :user, url: '/register' do |f| %>

  Username: <%= f.text_field :username %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<% if current_user && current_user.admin %>
<p>
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>
<% end %>

<p>
  <strong>Products:</strong>
  <% if @user.products.empty? %>
    No products yet.
<% else %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @user.products.each do |product| %>
        <td>  <%= link_to product.title,product %></td>
        <td>  <%= product.description %> </td>
        <td>  <%= product.price %></td>
      </tr>
      <% end %>
      <tbody>
      </table>
      <% end %>
    </p>

 <% if can? :update, @user %>
 <%= button_to 'Modify your account', modify_account_path(@user), class: "btn btn-primary" %>
 <br>
 <%= button_to 'Delete your account', delete_account_path, method: :delete,
  data: { confirm: 'Are you sure you want to delete your account? This action is irreversible' },
   class: "btn btn-danger"  %>

<% end %>