config/routes.rb
Rails.application.routes.draw do
resource :shopping_cart

  # get 'cart/add/:id' => 'cart#add',as: :cart_add

  resources :categories
  post '/rate' => 'rater#create', :as => 'rate'
  resources :products
root 'home#index'
  get '/register' => 'users#new'
  post '/register' => 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/account/:id', to: 'users#show', as: 'account'
  get '/account/:id/edit', to: 'users#edit', as: 'modify_account'
  patch '/account/:id', to: 'users#update'
  put '/account/:id', to: 'users#update'
  delete '/account/:id', to: 'users#destroy', as: 'delete_account'

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
mount_uploader :picture, PictureUploader
  belongs_to :user
  belongs_to :category
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  # validates :price, presence: true
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }
  validates :category_id, presence: true

  def self.search(search)
  if search
    # find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    where(['title LIKE ?', "%#{search}%"])
  end
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def grouped_cat
    @grouped_cat = Array.new
    @cat= Array.new
    Category.all.each do |cat|
     if !cat.parent_id
       @cat =[cat.name, Category.where("parent_id = ?", cat.id).map{|c| [c.name, c.id]}]
       @grouped_cat.push(@cat)
     end
   end
   return @grouped_cat
  end
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @grouped_cat= grouped_cat
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @grouped_cat= grouped_cat
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.category_id = params[:category_id]
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        # redirect_to new_product_path
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :picture)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="field">
   <%= f.label :picture %><br>
   <%= f.file_field :picture %>
 </div>
<%= select_tag(:category_id, grouped_options_for_select(@grouped_cat), :prompt => "Select a category") %> 
 <% if current_user.admin %>
<%= link_to 'Or create a new category', new_category_path %>
<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
 <ul class="collection with-header">
    <li class="collection-header"><h4>Products</h4></li>
       <% @products.each do |product| %>
       <li class="collection-item avatar">
     <% if !product.picture.file.nil? %>
       <%= image_tag product.picture.url, class:"circle" %>
     <% end %>
     <span class="title"> <%= link_to product.title,product %></span>
     <p><%= product.price %> € <br>
     </p>
   </li>
       <% end %>
   </ul>

<%= link_to "Browse by Category", categories_url %>
<!--
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Seller</th>
      <th>Description</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td> <% if !product.picture.file.nil? %>
           <%= image_tag product.picture.thumb.url %>
         <% end %> <%= link_to product.title,product %></td>
        <td><%=link_to product.category.name, product.category %></td>
        <td><%= link_to product.user.username, product.user %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->
<% if current_user %>
<%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>
  <div class="row">
  <%= form_for @product, class:"col s12" do |f| %>
<!-- # <%= render 'form', product: @product %> -->
<div class="row">
<div class="input-field col s12">
  <%= f.label :title %>
  <%= f.text_field :title,class:"validate" %>
</div>
</div>

<div class="row">
<div class="input-field col s12">
  <%= f.label :description %>
  <%= f.text_area :description,class:"materialize-textarea" %>
</div>
</div>

<div class="row">
  <%= f.label :price %>
  <%= f.text_field :price %>
</div>

 <!-- <%= f.label :picture %><br> -->

<div class="file-field input-field">
     <div class="btn">
       <span>Choose a picture</span>
       <%= f.file_field :picture %>
     </div>
     <div class="file-path-wrapper">
       <input class="file-path validate" type="text">
     </div>
   </div>
     <div class="input-field col s12">
<%= select_tag(:category_id, grouped_options_for_select(@grouped_cat), :prompt => "Select a category", class:"browser-default") %>
</div>
<% if current_user.admin %>
<%= link_to 'Or create a new category', new_category_path %>
<% end %>
<div class="actions">
  <%= f.submit "Create Product", class: "waves-effect waves-light btn" %>
</div>
<% end %>
</div>
<%= link_to 'Back', products_path %>
<script type="text/javascript">
$(document).ready(function() {
$('select').material_select();
});

</script>

app/views/products/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Seller:</strong>
  <%= link_to @product.user.username, @product.user %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>
<% if !@product.picture.file.nil?%>
<p>
  <strong>Picture:</strong> <br>
  <%= image_tag @product.picture.square.url %>
</p>
<% end %>
<%= link_to 'Add to cart', shopping_cart_path(:product_id => @product.id), :method => 'POST', class: "btn btn-primary" %>
 <% if can? :update, @product %>
<%= button_to 'Modify your product', edit_product_path(@product) , class: "btn btn-primary"%>
<%= button_to 'Delete product', product_path, method: :delete,
 data: { confirm: 'Are you sure you want to delete this product? This action is irreversible' },
  class: "btn btn-danger"  %>
<% end %>
<%= link_to 'all products', products_path %>