config/routes.rb
Rails.application.routes.draw do
resource :shopping_cart

  # get 'cart/add/:id' => 'cart#add',as: :cart_add

  resources :categories
  post '/rate' => 'rater#create', :as => 'rate'
  resources :products
root 'home#index'
  get '/register' => 'users#new'
  post '/register' => 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/account/:id', to: 'users#show', as: 'account'
  get '/account/:id/edit', to: 'users#edit', as: 'modify_account'
  patch '/account/:id', to: 'users#update'
  put '/account/:id', to: 'users#update'
  delete '/account/:id', to: 'users#destroy', as: 'delete_account'

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>Biddly</title>
    <%= csrf_meta_tags %>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-fixed">
   <nav>
     <div class="nav-wrapper">
       <a href="/" class="brand-logo">Selly</a>
       <ul class="right hide-on-med-and-down">
         <li><a href="/">Home</a></li>
         <li><%= link_to "Products", products_url %></li>
         <li> <i class="material-icons">shopping_cart</i> <%= link_to "Shopping Cart",shopping_cart_path%> </li>
         <% if !current_user %>
         <li><%= link_to "Register",   '/register' %></li>
         <li><%= link_to "Log in", '/login' %></li>
         <% else %>
         <li><%= link_to "My profile", account_path(current_user) %></li>
         <% if current_user.admin %>
         <li><%= link_to "Admin space", users_path %></li>
         <% end %>
       <li> <%= link_to "log out", '/logout', :method => :delete %></li>
         <% end %>
       </ul>
     </div>
   </nav>
 </div>

 <div class="container">
    <%- if flash.any? %>
 <%- flash.each do |key, value| %>
   <div class="alert alert-<%= key %>"><%= value %>
   </div>
 <%- end %>
<%- end %>
</div>
    <%= yield %>
    <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2016 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  </body>

</html>